language: python

python:
  - "3.3"
  - "3.6"

matrix:
  allow_failures:
    - python: "3.6"
  fast_finish: true

install:
  - pip install flake8
  - pip install pydocstyle

script:
  - flake8
  - pydocstyle
